### ISSUE TITLE
Errors in generators_example

### ISSUE THREAD

**Issue by giovannivolpe** [BenjaminMidtvedt/DeepTrack#47]
In generators_example, 

1) I had to change OpticalDevice to Fluorescence.

2) shape=(128, 128) does not work anymore, so I introduced the size of the figure in optics instead of in scatterer.

3) In plot.scatter, I had to invert position[1] and position[0] to make them coincide with the particle position in the figure.

Please, check these things (probably mostly due to the update of generators) and let me know what are your conclusions.

**Comment by BenjaminMidtvedt** [comment]
You're right on all counts. I missed updating this example after this revision. 2. is the recommended solution to the problem. And yes, positions are now inverted. Images are stored (row, column), which is why I thought it'd be intuitive to store positions as (y, x). If you prefer the other way around this is an easy change.
